peer/urls.py
from django.conf.urls import include, url, patterns


urlpatterns = patterns('peer.views',
    url(r'^$', 'index', name="index"),
    url(r'^browse/$', 'paper_index', name="paper_index"),
    url(r'^paper/(?P<paper_id>\d+)/$', 'paper_detail', name="paper_detail"),
    url(r'^submit/$', 'paper_submit', name="paper_submit"),
    url(r'^submission/$', 'submission_index', name="submission_index"),
    url(r'^paper/(?P<paper_id>\d+)/submit/$', 'revision_submit', name="revision_submit"),
)

project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

import peer
import account

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^u/', include("account.urls")),
    url(r'', include("peer.urls")),
]

urlpatterns += patterns('django.contrib.auth.views',
    url(r"^login/$", "login", name="login"),
    url(r"^logout/$", "logout", name="logout"),
    url(r'^reset/$', 'password_reset', name="password_reset"),
    url(r'^reset/sent/$', 'password_reset_done', name="password_reset_done"),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
    'password_reset_confirm'),
    url(r'^reset/done/$', 'password_reset_complete'),
)

urlpatterns += patterns('account.views',
    url(r"^register/$", "register_user", name="register"),
    url(r"^register/(?P<activation_key>[a-f0-9]*)$", "activate_user", name="activate"),
)


if settings.DEBUG:
    urlpatterns += patterns('',
            url(r'^media/(?P<path>.*)$',
                'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT, }),
            )

peer/models.py
import datetime

from django.db import models
from django.conf import settings


PENDING = 0
REJECTED = 1
REVISION = 2
ACCEPTED = 3

DECISION_CHOICES = (
    (REJECTED, "Rejected"),
    (REVISION, "Revision"),
    (ACCEPTED, "Accepted"),
)
STATUS_CHOICES = ((PENDING, "Pending"), ) + DECISION_CHOICES


class Paper(models.Model):
    title = models.CharField(max_length=255)
    abstract = models.TextField(max_length=1024)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    submitted = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(auto_now=False, null=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=PENDING)

    def is_public(self):
        return self.status == ACCEPTED

    def is_reviewed(self):
        return self.status != PENDING

    def needs_revision(self):
        return self.status == REVISION

    def update_status(self, status):
        self.status = status
        if self.status == ACCEPTED:
            self.published = datetime.datetime.now()
        self.save()

    def get_current_url(self):
        return self.revisions.latest().pdf_file.url


class Revision(models.Model):
    comments = models.TextField(max_length=1024*1024)
    pdf_file = models.FileField(upload_to="papers")
    submitted = models.DateTimeField(auto_now=True)
    paper = models.ForeignKey(Paper, related_name="revisions")
    hash_value = models.CharField(max_length=64, null=True)

    class Meta:
        get_latest_by = "submitted"


class Review(models.Model):
    paper = models.ForeignKey(Paper, related_name="reviews")
    editor = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="reviews")
    comments = models.TextField(max_length=1024*1024)
    decision = models.IntegerField(choices=DECISION_CHOICES)
    submitted = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        get_latest_by = "submitted"

peer/forms.py
from django import forms

from models import Paper, Revision

class PaperForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = ("title", "abstract")


class RevisionForm(forms.ModelForm):
    
    class Meta:
        model = Revision
        fields = ("comments", "pdf_file")

peer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from models import Paper, Revision, PENDING
from forms import PaperForm, RevisionForm


def index(request):
    c = {}
    return render(request, "peer/index.html", c)


def paper_index(request):
    new_papers = Paper.objects.filter(published__isnull=False).order_by('-pk')[:10]
    c = {
        "papers": new_papers,
    }
    return render(request, "peer/paper_index.html", c)


def paper_detail(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    if request.user == paper.author or paper.is_public():
        c = {"paper": paper}
        return render(request, "peer/paper_detail.html", c)
    else:
        raise Http404("Paper does not exist.")


@login_required
def paper_submit(request):
    if request.method == "POST":
        paper = Paper(author=request.user)
        paper_form = PaperForm(request.POST, instance=paper)
        rev = Revision(paper=paper)
        rev_form = RevisionForm(request.POST, request.FILES, instance=rev)
        
        # prevent short circuit
        paper_valid = paper_form.is_valid()
        rev_valid = rev_form.is_valid()
        

        if paper_valid and rev_valid:
            new_paper = paper_form.save()
            rev = Revision(paper=new_paper)
            rev_form = RevisionForm(request.POST, request.FILES, instance=rev)
            rev_form.save()
            # log
            return redirect(submission_index)
    else:
        paper_form = PaperForm()
        rev_form = RevisionForm()

    c = {
        "paper_form": paper_form,
        "rev_form": rev_form,
    }
    return render(request, "peer/submit_paper.html", c)


@login_required
def submission_index(request):
    c = {
        "papers": request.user.paper_set.all(),
    }
    return render(request, "peer/paper_index.html", c)


def revision_submit(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id, author=request.user)
    if request.method == "POST":
        revision = Revision(paper=paper)
        form = RevisionForm(request.POST, request.FILES, instance=revision)

        if form.is_valid():
            form.save()
            paper.update_status(PENDING)
            # log
            return redirect(submission_index)
    else:
        form = RevisionForm()

    c = {
        "form": form,
    }
    return render(request, "peer/submit_revision.html", c)

peer/templates/peer/base.html
{% extends "base.html" %}

peer/templates/peer/index.html
{% extends "peer/base.html" %}

{% block title %}Peer{% endblock %}

{% block landing %}
<div class="intro-header">
    <div class="container">
        <h1><span class="rwd-line">Peer</span><span class="rwd-line">Rev</span></h1>
        <h3>An Automated Academic Journal</h3>
        <p>Yup, that is right, all the reviewers are entities that are lacking in the flesh department.</p>
  </div>
</div>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h2>Really? No more mean reviewers?</h2>
            <p>That is correct, we have eliminated biased human reviewers with a perfectly unbiased algorithm that will properly review academic papers.</p>
        </div>
        <div class="col-lg-10">
            <h2>So, how does it work?</h2>
            <p>Fancy math, cool algorithms, and two drops of black magic.</p>
        </div>
        <div class="col-lg-10">
            <h2>Right. So, um, why?</h2>
            <p>Because we want to change the world, er, well, not really. I guess just because we have the technology!</p>
        </div>
        <div class="col-lg-10">
            <h2>Okay, I'm sold, where do I get started?</h2>
            <p>I'm glad you asked. <a href="{% url 'register' %}">Right here.</a></p>
        </div>
    </div>
</div>
{% endblock %}

peer/templates/peer/paper_detail.html
{% extends "peer/base.html" %}

{% block title %}Peer{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="title">{{ paper.title }}</div>
        <div class="author">{{ paper.author }} | {% if paper.is_public %}Accepted: {{ paper.published }}{% else %}Submitted: {{ paper.submitted }}{% endif %}</div>
        <div class="abstract">{{ paper.abstract }}</div>
        {% if request.user == paper.author %}
            <div class="status">
            {% if paper.needs_revision %}
                <a href="{% url 'revision_submit' paper.pk %}">
                    Click to Submit a Revision
                </a>
            {% else %}
                {{ paper.get_status_display }}
            {% endif %}
            </div>
            <p>
            <div class="list-group">
                {% if paper.is_reviewed %}
                    <a class="list-group-item collapse-data-btn" data-toggle="collapse" href="#reviews">
                        Click to see reviews<b class="caret"></b></a>
                    <dl id="reviews" class="dl-horizontal collapse">
                {% for review in paper.reviews.all %}
                      <dt>{{ review.get_decision_display }}</dt>
                      <dd>{{ review.comments }}</dd>
                {% endfor %}
                    </dl>
                {% endif %}
                <a class="list-group-item collapse-data-btn" data-toggle="collapse" href="#revisions">
                        Click to see revisions<b class="caret"></b></a>
                <div id="revisions" class="collapse">
                {% for revision in paper.revisions.all %}
                    <div><a href="{{ revision.pdf_file.url }}">Revision {{ forloop.counter0 }}</a></div>
                {% endfor %}
                </div>
            </div>    
        {% endif %}
        <div class="row">
            <div class="col-xs-6">
                <a class="btn btn-lg btn-primary btn-block" href="{{ paper.get_current_url }}">Get PDF</a>
            </div>
            <div class="col-xs-6">
                <a class="btn btn-lg btn-primary btn-block" href="">Cite</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

peer/templates/peer/paper_index.html
{% extends "peer/base.html" %}

{% block title %}Peer{% endblock %}

{% block content %}
<div class="container">
    {% for paper in papers %}
    <div class="row">
        <div class="title"><a href="{% url 'paper_detail' paper.id %}">{{ paper.title }}</a></div>
        <div class="author">{{ paper.author }} | {% if paper.is_public %}Accepted: {{ paper.published }}{% else %}Submitted: {{ paper.submitted }}{% endif %}</div>
        <div class="abstract">{{ paper.abstract }}</div>
        {% if request.user == paper.author %}
        <div class="status">{{ paper.get_status_display }}</div>
        {% endif %}
        <div class="detail">{{ paper.url }}</div>
    </div>
    <p>
    {% endfor %}
</div>
{% endblock %}

peer/templates/peer/submit_paper.html
{% extends "peer/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Peer{% endblock %}

{% block content %}

<form enctype="multipart/form-data" action="." method="post">
    {% csrf_token %}
    {{ paper_form | crispy }}
    {{ rev_form | crispy }}
    <div class="row">
        <div class="col-xs-6">
            <button class="btn btn-lg btn-primary btn-block"
            type="submit">Submit</button>
        </div>
        <div class="col-xs-6">
            <button class="btn btn-lg btn-block" type="reset">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

peer/templates/peer/submit_revision.html
{% extends "peer/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Peer{% endblock %}

{% block content %}

<form enctype="multipart/form-data" action="." method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <div class="row">
        <div class="col-xs-6">
            <button class="btn btn-lg btn-primary btn-block"
            type="submit">Submit</button>
        </div>
        <div class="col-xs-6">
            <button class="btn btn-lg btn-block" type="reset">Reset</button>
        </div>
    </div>
</form>
{% endblock %}